import "./style.css";

/**
 * This file is a starting point, you are encourage to edit it to fit your requirements.
 *
 * You can see below the code used to load a scene.
 *
 * Learn more about Polygonjs API: https://polygonjs.com/docs/api/
 *
 */

// This imports the loading function for the scene, from the files that are autogenerated
// by the editor when you save your scene.
import { fetchSceneAndMount_scene_01 } from "./polygonjs/scenes/scene_01/autogenerated/fetchSceneAndMount";

// Here we load the scene on the DOM element with the id 'app'.
fetchSceneAndMount_scene_01({
	domElement: "app",
	baseUrl: import.meta.env.BASE_URL,
});
